CREATE TYPE categoria_enum AS ENUM ('PROGRAMAÇÃO', 'JAVA', 'SPRING_BOOT',
	'IA', 'DESENVOLVIMENTO_PESSOAL', 'BANCO_DE_DADOS', 'SEGURANCA');

CREATE TABLE curso (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    categoria VARCHAR(20) NOT NULL

);