INSERT INTO curso (nome, categoria) VALUES
('Lógica de Programação para Iniciantes', 'PROGRAMAÇÃO'),
('Introdução ao Java', 'JAVA'),
('Spring Boot Essentials', 'SPRING_BOOT'),
('Fundamentos de Inteligência Artificial', 'IA'),
('Produtividade e Gestão de Tempo', 'DESENVOLVIMENTO_PESSOAL'),
('Modelagem de Dados Relacional', 'BANCO_DE_DADOS'),
('Segurança da Informação para Iniciantes', 'SEGURANCA'),
('Java Avançado com Orientação a Objetos', 'JAVA'),
('APIs REST com Spring Boot', 'SPRING_BOOT'),
('Chatbots com IA Generativa', 'IA'),
('Clean Code e Boas Práticas de Programação', 'PROGRAMAÇÃO'),
('Java para Web com Servlets e JSP', 'JAVA'),
('Spring Boot com Spring Security', 'SPRING_BOOT'),
('Machine Learning na Prática', 'IA'),
('Comunicação Eficaz e Oratória', 'DESENVOLVIMENTO_PESSOAL'),
('SQL Avançado para Análise de Dados', 'BANCO_DE_DADOS'),
('Criptografia e Segurança de Dados', 'SEGURANCA'),
('Estruturas de Dados em Java', 'JAVA'),
('Deploy de Aplicações Spring Boot com Docker', 'SPRING_BOOT'),
('Visão Computacional com Python e IA', 'IA');